export const TEMPLATESPERPAGE = 15;

export const ORDERTYPES = { DEFAULT: 'DEFAULT', ASCENDING: 'ASCENDING', DESCENDING: 'DESCENDING' };

export const DATETYPES = { DEFAULT: 'DEFAULT', ASCENDING: 'ASCENDING', DESCENDING: 'DESCENDING' };

export const CATEGROYTYPES = {
  ALL: 'ALL', ECOMMERCE: 'ECOMMERCE', EDUCATION: 'EDUCATION', AGRICULTURE: 'AGRICULTURE',
};
